name: "smoketest Action"
description: "Runs smoketest with common setup steps"
inputs:
  profile:
    description: "Profile to use"
    required: true
  paths:
    description: "Test paths"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Nextflow
      uses: nf-core/setup-nextflow@v2
      with:
        version: "${{ env.NXF_VERSION }}"

    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    - name: Set up Singularity Dirs
      if: contains(inputs.profile, 'singularity')
      shell: bash
      run: |
        mkdir -p $NXF_SINGULARITY_CACHEDIR
        mkdir -p $NXF_SINGULARITY_LIBRARYDIR


    - name: Run pipeline smoketest
      shell: bash
      env:
        NFT_DIFF: ${{ env.NFT_DIFF }}
        NFT_DIFF_ARGS: ${{ env.NFT_DIFF_ARGS }}
        NFT_WORKDIR: ${{ env.NFT_WORKDIR }}
      run: |
        nextflow run main.nf \
          -profile test,${{ inputs.profile }} 

    - name: Clean up
      if: always()
      shell: bash
      run: |
        sudo rm -rf .nextflow work results
